export type SdkworkSubscriptionLocale = "en-US" | "zh-CN";
export type SdkworkSubscriptionMessagesOverrides = DeepPartial<SdkworkSubscriptionMessages>;
export interface SdkworkSubscriptionMessages {
    actions: {
        activateMembership: string;
        backToPlans: string;
        clearCoupon: string;
        confirmPayment: string;
        confirmRenewal: string;
        continueToCheckout: string;
        purchase: string;
        renew: string;
        selectPlan: string;
        selectedPlan: string;
        upgrade: string;
    };
    checkoutPanel: {
        checkoutErrorTitle: string;
        description: string;
        lockedBadge: string;
        safePaymentLabel: string;
        signInRequiredDescription: string;
        signInRequiredTitle: string;
        title: string;
    };
    common: {
        current: string;
        days: string;
        flexibleDuration: string;
        noValue: string;
        points: string;
    };
    compareTable: {
        categoryGeneration: string;
        categorySpeed: string;
        categorySupport: string;
        dailyPoints: string;
        description: string;
        discount20Off: string;
        emptyDescription: string;
        featureHeader: string;
        freePlan: string;
        history7Days: string;
        history30Days: string;
        history90Days: string;
        historyForever: string;
        historyRetention: string;
        noWatermark: string;
        planBasic: string;
        planPremium: string;
        planStandard: string;
        pointsDaily: string;
        pointsPerMonth: string;
        refundGuarantee: string;
        seedanceVip: string;
        seedancePro: string;
        standardSpeed: string;
        supportDedicated: string;
        supportEarlyAccess: string;
        title: string;
        videoDuration: string;
        vipLane: string;
        apiAccess: string;
        image2K: string;
        image4K: string;
        fastLane: string;
    };
    couponList: {
        description: string;
        eyebrow: string;
        minSpendLabel: string;
        noCoupons: string;
        noMinimumSpend: string;
        offerFallback: string;
        removeCoupon: string;
        selectedOffer: string;
        tapToUse: string;
    };
    format: {
        couponCountReadyPlural: string;
        couponCountReadySingular: string;
        couponDaysLeft: string;
        currentLevelRemaining: string;
        discountRate: string;
    };
    hero: {
        availablePlansLabel: string;
        currentLevelLabel: string;
        currentPointsLabel: string;
        currentStatusLabel: string;
        dailyPointsLabel: string;
        description: string;
        eyebrow: string;
        freeTierLabel: string;
        freeUserTitle: string;
        freeUserTitleHighlight: string;
        freeUserTitleSuffix: string;
        guestDescription: string;
        memberBadgeLabel: string;
        memberDescription: string;
        membershipBalanceLabel: string;
        pointsUnit: string;
        premiumMembershipActive: string;
        readyForPremiumActivation: string;
        remainingDaysLabel: string;
        thanksForSupportLabel: string;
        title: string;
        totalSpentLabel: string;
        upgradeBadgeLabel: string;
        welcomeBackLabel: string;
    };
    catalog: {
        categoryAll: string;
        categoryCommunity: string;
        categoryLabel: string;
        categoryToken: string;
    };
    levelGrid: {
        empty: string;
        eyebrow: string;
        levelFallback: string;
        title: string;
    };
    page: {
        agreementText: string;
        confirmOrderTitle: string;
        confirmOrderDescription: string;
        durationLabel: string;
        errorTitle: string;
        includedPointsLabel: string;
        loading: string;
        title: string;
    };
    pendingPayment: {
        amountLabel: string;
        description: string;
        dismiss: string;
        openCashier: string;
        orderLabel: string;
        packageFallback: string;
        qrLabel: string;
        refresh: string;
        title: string;
    };
    paymentMethods: {
        alipayLabel: string;
        appRedirectLabel: string;
        description: string;
        desktopPayment: string;
        eyebrow: string;
        nativeLabel: string;
        noMethods: string;
        openInPaymentApp: string;
        pcWebLabel: string;
        recommended: string;
        scanToPay: string;
        selectedState: string;
        tapToUse: string;
        wechatPayLabel: string;
    };
    planGrid: {
        benefitsEmpty: string;
        benefitsEyebrow: string;
        benefitFallback: string;
        currentBalanceLabel: string;
        currentPlanButton: string;
        currentTag: string;
        dailyRewardsTag: string;
        entryTier: string;
        freeBaselineButton: string;
        freeDescription: string;
        freePlanName: string;
        freeTierBadge: string;
        freeUseButton: string;
        freeMembershipDescription: string;
        freeMembershipTitle: string;
        noPlans: string;
        noRecurringCharge: string;
        recommendedBadge: string;
        savingsLabel: string;
        selectPlanButton: string;
        signInToActivatePremiumCheckout: string;
        title: string;
        titleEyebrow: string;
    };
    priceSummary: {
        amountDueLabel: string;
        couponDeductionLabel: string;
        originalPriceLabel: string;
        paymentRailLabel: string;
    };
    selectedPlan: {
        eyebrow: string;
        fallbackDescription: string;
        noPlanSelectedDescription: string;
        noPlanSelectedTitle: string;
    };
    stageShell: {
        actionLabel: string;
        availablePlansLabel: string;
        checkoutAmountLabel: string;
        checkoutDescription: string;
        checkoutStatusDescription: string;
        checkoutTitle: string;
        couponsReadyLabel: string;
        currentLevelLabel: string;
        descriptionLockedPackage: string;
        descriptionNoPlanSelected: string;
        durationLabel: string;
        includedPointsLabel: string;
        lockedBadge: string;
        lockedPackageLabel: string;
        planStageDescription: string;
        planStageTitle: string;
        plannedActionLabel: string;
        priceLabel: string;
        purchaseStagesEyebrow: string;
        readyDescription: string;
        readyTitle: string;
        selectedPackageLabel: string;
        signInRequiredDescription: string;
        signInRequiredTitle: string;
        stepCheckoutDescription: string;
        stepCheckoutTitle: string;
        stepPlanDescription: string;
        stepPlanTitle: string;
        twoStepFlow: string;
    };
    service: {
        checkoutFailed: string;
        loadDashboardFailed: string;
        purchaseFailed: string;
        renewFailed: string;
        requestFailed: string;
        selectPlanBeforeContinue: string;
        signInRequired: string;
        upgradeFailed: string;
    };
    status: {
        available: string;
        expired: string;
        inactive: string;
        used: string;
    };
}
type DeepPartial<T> = {
    [K in keyof T]?: T[K] extends (...args: never[]) => unknown ? T[K] : T[K] extends object ? DeepPartial<T[K]> : T[K];
};
export declare function normalizeSdkworkSubscriptionLocale(locale?: string | null): SdkworkSubscriptionLocale;
export declare function createSdkworkSubscriptionMessages(locale?: string | null, overrides?: SdkworkSubscriptionMessagesOverrides): SdkworkSubscriptionMessages;
export {};
//# sourceMappingURL=subscription-copy.d.ts.map