function isRecord(value) {
    return Boolean(value) && typeof value === "object" && !Array.isArray(value);
}
function mergeDeep(base, overrides) {
    if (!overrides) {
        return base;
    }
    const output = {
        ...base,
    };
    for (const [key, value] of Object.entries(overrides)) {
        if (value === undefined) {
            continue;
        }
        const baseValue = output[key];
        output[key] = isRecord(baseValue) && isRecord(value)
            ? mergeDeep(baseValue, value)
            : value;
    }
    return output;
}
const EN_US_MESSAGES = {
    actions: {
        activateMembership: "Activate membership",
        backToPlans: "Back to plans",
        clearCoupon: "Remove coupon",
        confirmPayment: "Confirm payment",
        confirmRenewal: "Confirm renewal",
        continueToCheckout: "Continue to checkout",
        purchase: "Purchase",
        renew: "Renew",
        selectPlan: "Select plan",
        selectedPlan: "Selected",
        upgrade: "Upgrade",
    },
    checkoutPanel: {
        checkoutErrorTitle: "Checkout error",
        description: "Package details, coupon state, and payment rail stay synchronized with the selected subscription package.",
        lockedBadge: "Locked checkout",
        safePaymentLabel: "Secure payment",
        signInRequiredDescription: "Membership checkout requires an authenticated session.",
        signInRequiredTitle: "Sign in required",
        title: "Checkout summary",
    },
    common: {
        current: "Current",
        days: "days",
        flexibleDuration: "Flexible duration",
        noValue: "--",
        points: "credits",
    },
    compareTable: {
        categoryGeneration: "AI Generation",
        categorySpeed: "Speed & Privileges",
        categorySupport: "Service & Support",
        dailyPoints: "Daily bonus credits",
        description: "Compare benefits across all tiers to find the right plan.",
        discount20Off: "20% off",
        emptyDescription: "Benefit comparison will appear once membership catalog data is available.",
        featureHeader: "Benefit",
        freePlan: "Free",
        history7Days: "7 days",
        history30Days: "30 days",
        history90Days: "90 days",
        historyForever: "Unlimited",
        historyRetention: "History retention",
        noWatermark: "Watermark-free export",
        planBasic: "Basic",
        planPremium: "Premium",
        planStandard: "Standard",
        pointsDaily: "50/day",
        pointsPerMonth: "{count}/month",
        refundGuarantee: "Money-back guarantee",
        seedanceVip: "Seedance 2.0 VIP",
        seedancePro: "Seedance 1.5 Pro",
        standardSpeed: "Standard generation lane",
        supportDedicated: "Dedicated support",
        supportEarlyAccess: "Early access to new features",
        title: "Plan comparison",
        videoDuration: "Video generation length",
        vipLane: "VIP priority lane",
        apiAccess: "API quota",
        image2K: "2K image generation",
        image4K: "4K HD image generation",
        fastLane: "Fast generation lane",
    },
    couponList: {
        description: "Apply the strongest eligible offer before payment.",
        eyebrow: "Coupon selection",
        minSpendLabel: "Min spend",
        noCoupons: "No checkout coupons are currently available.",
        noMinimumSpend: "No minimum spend",
        offerFallback: "Offer",
        removeCoupon: "Remove coupon",
        selectedOffer: "Selected offer",
        tapToUse: "Tap to use",
    },
    format: {
        couponCountReadyPlural: "{count} coupons ready for checkout",
        couponCountReadySingular: "{count} coupon ready for checkout",
        couponDaysLeft: "{count} {days} left",
        currentLevelRemaining: "{count} {days} remaining",
        discountRate: "{value} discount",
    },
    hero: {
        availablePlansLabel: "Available plans",
        currentLevelLabel: "Current level",
        currentPointsLabel: "Current credits",
        currentStatusLabel: "Current status",
        dailyPointsLabel: "Daily login rewards",
        description: "Select a membership plan, apply the best coupon, and lock one premium checkout flow that any SDKWORK desktop app can embed.",
        eyebrow: "Premium checkout",
        freeTierLabel: "Free user",
        freeUserTitle: "Unlock ",
        freeUserTitleHighlight: "unlimited creation",
        freeUserTitleSuffix: " potential",
        guestDescription: "Join membership to unlock all AI models, faster generation speeds, and exclusive credit quotas, unleashing your creative potential.",
        memberBadgeLabel: "VIP",
        memberDescription: "Your membership benefits are about to expire. Renew now to continue enjoying exclusive AI creation capabilities.",
        membershipBalanceLabel: "Membership balance",
        pointsUnit: " credits",
        premiumMembershipActive: "Premium membership active",
        readyForPremiumActivation: "Ready for premium activation",
        remainingDaysLabel: "{count} days remaining",
        thanksForSupportLabel: "Thank you for your support",
        title: "Subscription center",
        totalSpentLabel: "Total spent",
        upgradeBadgeLabel: "Upgrade",
        welcomeBackLabel: "Welcome back, ",
    },
    catalog: {
        categoryAll: "All",
        categoryCommunity: "Community",
        categoryLabel: "Plan family",
        categoryToken: "Token Plan",
    },
    levelGrid: {
        empty: "Membership level comparison will appear when the current runtime exposes membership levels.",
        eyebrow: "Membership ladder",
        levelFallback: "Membership level",
        title: "Membership levels",
    },
    page: {
        agreementText: "By subscribing, you agree to the Membership Service Agreement and Auto-Renewal Service Agreement. Subscriptions can be cancelled at any time.",
        confirmOrderTitle: "Order confirmation",
        confirmOrderDescription: "Confirm your selected package and complete payment.",
        durationLabel: "Duration",
        errorTitle: "Subscription center error",
        includedPointsLabel: "Included credits",
        loading: "Loading subscription center...",
        title: "Subscription center",
    },
    pendingPayment: {
        amountLabel: "Amount due",
        description: "Complete payment in the cashier or scan the QR payload, then refresh membership status.",
        dismiss: "Dismiss",
        openCashier: "Open cashier",
        orderLabel: "Order",
        packageFallback: "Selected package",
        qrLabel: "QR payment payload",
        refresh: "Refresh status",
        title: "Payment pending",
    },
    paymentMethods: {
        alipayLabel: "Alipay",
        appRedirectLabel: "App redirect",
        description: "Choose the live payment rail exposed by the commerce runtime.",
        desktopPayment: "Desktop payment",
        eyebrow: "Payment method",
        nativeLabel: "Native",
        noMethods: "Payment methods will appear when the runtime exposes a live payment contract.",
        openInPaymentApp: "Open in payment app",
        pcWebLabel: "PC Web",
        recommended: "Recommended",
        scanToPay: "Scan to pay",
        selectedState: "Currently selected",
        tapToUse: "Tap to use",
        wechatPayLabel: "WeChat Pay",
    },
    planGrid: {
        benefitsEmpty: "Benefit highlights will appear when the membership catalog exposes them.",
        benefitsEyebrow: "Premium benefits",
        benefitFallback: "Premium entitlement",
        currentBalanceLabel: "Current balance",
        currentPlanButton: "Current plan",
        currentTag: "Current",
        dailyRewardsTag: "Daily rewards",
        entryTier: "Entry tier",
        freeBaselineButton: "Free baseline",
        freeDescription: "Compare free and premium before checkout.",
        freePlanName: "Free",
        freeTierBadge: "Free tier",
        freeUseButton: "Continue with free",
        freeMembershipDescription: "Compare free and premium before checkout. Keep a zero-commit baseline for lightweight usage.",
        freeMembershipTitle: "Free membership",
        noPlans: "No subscription plans are currently available.",
        noRecurringCharge: "No recurring charge",
        recommendedBadge: "Recommended",
        savingsLabel: "Save ",
        selectPlanButton: "Select plan",
        signInToActivatePremiumCheckout: "Sign in to activate premium checkout",
        title: "Choose a premium package",
        titleEyebrow: "Plan selection",
    },
    priceSummary: {
        amountDueLabel: "Amount due",
        couponDeductionLabel: "Coupon deduction",
        originalPriceLabel: "Original price",
        paymentRailLabel: "Payment rail",
    },
    selectedPlan: {
        eyebrow: "Selected package",
        fallbackDescription: "Premium subscription package",
        noPlanSelectedDescription: "Choose a subscription plan to unlock checkout.",
        noPlanSelectedTitle: "No plan selected",
    },
    stageShell: {
        actionLabel: "Action",
        availablePlansLabel: "Available plans",
        checkoutAmountLabel: "Checkout amount",
        checkoutDescription: "The selected package is now locked for payment. Coupons, amount due, and payment method stay synchronized with this package until checkout completes.",
        checkoutStatusDescription: "Return to plans if you need to switch package before payment.",
        checkoutTitle: "Locked checkout",
        couponsReadyLabel: "Coupons ready",
        currentLevelLabel: "Current level",
        descriptionLockedPackage: "Return to the previous stage to choose a package before checkout.",
        descriptionNoPlanSelected: "Choose a subscription plan to continue into checkout.",
        durationLabel: "Duration",
        includedPointsLabel: "Included credits",
        lockedBadge: "Locked package",
        lockedPackageLabel: "Locked package",
        planStageDescription: "Compare packages, keep the current membership baseline in view, and move into checkout only when the selected package is ready.",
        planStageTitle: "Select a premium package",
        plannedActionLabel: "Planned action",
        priceLabel: "Price",
        purchaseStagesEyebrow: "Purchase stages",
        readyDescription: "Package details stay locked after you enter checkout, but you can always return to this stage to switch packages before paying.",
        readyTitle: "Ready to continue",
        selectedPackageLabel: "Selected package",
        signInRequiredDescription: "Checkout stays available after sign-in. You can still compare packages before authenticating.",
        signInRequiredTitle: "Sign in required",
        stepCheckoutDescription: "Lock the package, apply coupons, and confirm payment.",
        stepCheckoutTitle: "2. Checkout",
        stepPlanDescription: "Compare free and premium packages before payment.",
        stepPlanTitle: "1. Select plan",
        twoStepFlow: "2-step flow",
    },
    service: {
        checkoutFailed: "Subscription checkout failed.",
        loadDashboardFailed: "Failed to load subscription center.",
        purchaseFailed: "Failed to purchase subscription.",
        renewFailed: "Failed to renew subscription.",
        requestFailed: "Request failed.",
        selectPlanBeforeContinue: "Select a subscription plan before continuing.",
        signInRequired: "Please sign in to manage subscriptions.",
        upgradeFailed: "Failed to upgrade subscription.",
    },
    status: {
        available: "Available",
        expired: "Expired",
        inactive: "Inactive",
        used: "Used",
    },
};
const ZH_CN_MESSAGES = {
    actions: {
        activateMembership: "开通会员",
        backToPlans: "返回套餐",
        clearCoupon: "移除优惠券",
        confirmPayment: "确认支付",
        confirmRenewal: "确认续费",
        continueToCheckout: "继续前往结算",
        purchase: "购买",
        renew: "续费",
        selectPlan: "选择套餐",
        selectedPlan: "已选择",
        upgrade: "升级",
    },
    checkoutPanel: {
        checkoutErrorTitle: "结算异常",
        description: "套餐详情、优惠状态与支付通道会始终与当前选中的订阅套餐保持同步。",
        lockedBadge: "锁定结算",
        safePaymentLabel: "安全支付",
        signInRequiredDescription: "会员结算需要先完成登录。",
        signInRequiredTitle: "需要登录",
        title: "结算摘要",
    },
    common: {
        current: "当前",
        days: "天",
        flexibleDuration: "时长灵活",
        noValue: "--",
        points: "算力积分",
    },
    compareTable: {
        categoryGeneration: "AI 生成能力",
        categorySpeed: "生成速度与特权",
        categorySupport: "服务与支持",
        dailyPoints: "每日赠送算力积分",
        description: "详细对比各套餐权益，选择最适合你的方案。",
        discount20Off: "8折",
        emptyDescription: "会员权益目录加载后将显示套餐对比。",
        featureHeader: "权益项目",
        freePlan: "免费版",
        history7Days: "7天",
        history30Days: "30天",
        history90Days: "90天",
        historyForever: "永久",
        historyRetention: "生成历史保留",
        noWatermark: "无水印导出",
        planBasic: "基础会员",
        planPremium: "高级会员",
        planStandard: "标准会员",
        pointsDaily: "50/天",
        pointsPerMonth: "{count}/月",
        refundGuarantee: "无忧退款保障",
        seedanceVip: "Seedance 2.0 VIP",
        seedancePro: "Seedance 1.5 Pro",
        standardSpeed: "标准生成通道",
        supportDedicated: "专属客服通道",
        supportEarlyAccess: "新功能优先体验",
        title: "套餐权益对比",
        videoDuration: "视频生成时长",
        vipLane: "VIP专属通道",
        apiAccess: "API调用额度",
        image2K: "图片2K生成",
        image4K: "图片4K高清生成",
        fastLane: "快速生成通道",
    },
    couponList: {
        description: "支付前优先应用当前可用的最优优惠。",
        eyebrow: "优惠券选择",
        minSpendLabel: "满",
        noCoupons: "当前没有可用于结算的优惠券。",
        noMinimumSpend: "无门槛",
        offerFallback: "优惠",
        removeCoupon: "移除优惠券",
        selectedOffer: "已选优惠",
        tapToUse: "点击使用",
    },
    format: {
        couponCountReadyPlural: "有 {count} 张优惠券可用于结算",
        couponCountReadySingular: "有 {count} 张优惠券可用于结算",
        couponDaysLeft: "剩余 {count} {days}",
        currentLevelRemaining: "剩余 {count} {days}",
        discountRate: "{value} 折",
    },
    hero: {
        availablePlansLabel: "可选套餐",
        currentLevelLabel: "当前等级",
        currentPointsLabel: "当前算力积分",
        currentStatusLabel: "当前状态",
        dailyPointsLabel: "每日登录领取算力积分",
        description: "选择会员套餐、应用最优优惠券，并锁定一套可被任意 SDKWORK 桌面应用复用的高级订阅结算流。",
        eyebrow: "高级会员结算",
        freeTierLabel: "免费用户",
        freeUserTitle: "解锁",
        freeUserTitleHighlight: "无限创作",
        freeUserTitleSuffix: "可能",
        guestDescription: "加入会员，畅享全部AI模型、更快生成速度和专属算力积分额度，释放您的创作潜能。",
        memberBadgeLabel: "VIP会员",
        memberDescription: "您的会员权益即将到期，立即续费继续享受专属AI创作能力。",
        membershipBalanceLabel: "会员资产",
        pointsUnit: "算力积分",
        premiumMembershipActive: "当前为高级会员",
        readyForPremiumActivation: "已准备好开通高级会员",
        remainingDaysLabel: "剩余 {count} 天",
        thanksForSupportLabel: "感谢您的支持",
        title: "订阅中心",
        totalSpentLabel: "累计消费",
        upgradeBadgeLabel: "升级会员",
        welcomeBackLabel: "欢迎回来，",
    },
    catalog: {
        categoryAll: "全部",
        categoryCommunity: "圈子社区",
        categoryLabel: "套餐体系",
        categoryToken: "Token 套餐",
    },
    levelGrid: {
        empty: "当运行时提供会员等级数据后，这里会展示完整的等级对比。",
        eyebrow: "会员阶梯",
        levelFallback: "会员等级",
        title: "会员等级",
    },
    page: {
        agreementText: "开通即表示同意《会员服务协议》和《自动续费服务协议》。连续订阅可随时取消。",
        confirmOrderTitle: "订单确认",
        confirmOrderDescription: "确认您选择的套餐并完成支付。",
        durationLabel: "有效期",
        errorTitle: "订阅中心异常",
        includedPointsLabel: "包含算力积分",
        loading: "正在加载订阅中心...",
        title: "订阅中心",
    },
    pendingPayment: {
        amountLabel: "待支付金额",
        description: "请在收银台完成支付或扫描二维码，然后刷新会员状态。",
        dismiss: "关闭",
        openCashier: "打开收银台",
        orderLabel: "订单号",
        packageFallback: "已选套餐",
        qrLabel: "扫码支付内容",
        refresh: "刷新状态",
        title: "等待支付",
    },
    paymentMethods: {
        alipayLabel: "支付宝",
        appRedirectLabel: "应用跳转",
        description: "选择由商业化运行时暴露的实时支付通道。",
        desktopPayment: "桌面支付",
        eyebrow: "支付方式",
        nativeLabel: "原生支付",
        noMethods: "当运行时暴露实时支付接口后，这里会显示可用支付方式。",
        openInPaymentApp: "在支付应用中打开",
        pcWebLabel: "PC 网页",
        recommended: "推荐",
        scanToPay: "扫码支付",
        selectedState: "当前已选",
        tapToUse: "点击使用",
        wechatPayLabel: "微信支付",
    },
    planGrid: {
        benefitsEmpty: "当会员目录暴露权益亮点后，这里会显示完整权益说明。",
        benefitsEyebrow: "高级会员权益",
        benefitFallback: "会员权益",
        currentBalanceLabel: "当前余额",
        currentPlanButton: "当前方案",
        currentTag: "当前",
        dailyRewardsTag: "每日奖励",
        entryTier: "入门层级",
        freeBaselineButton: "免费基线",
        freeDescription: "在结算前比较免费版与高级版。",
        freePlanName: "免费版",
        freeTierBadge: "免费层级",
        freeUseButton: "继续使用免费版",
        freeMembershipDescription: "在结算前清晰比较免费版与高级版，让轻量使用场景始终保留零承诺基线。",
        freeMembershipTitle: "免费会员",
        noPlans: "当前暂无可订阅套餐。",
        noRecurringCharge: "无循环扣费",
        recommendedBadge: "推荐",
        savingsLabel: "省",
        selectPlanButton: "选择套餐",
        signInToActivatePremiumCheckout: "登录后即可开通高级会员结算",
        title: "选择高级会员套餐",
        titleEyebrow: "套餐选择",
    },
    priceSummary: {
        amountDueLabel: "应付金额",
        couponDeductionLabel: "优惠抵扣",
        originalPriceLabel: "原价",
        paymentRailLabel: "支付通道",
    },
    selectedPlan: {
        eyebrow: "已选套餐",
        fallbackDescription: "高级会员订阅套餐",
        noPlanSelectedDescription: "选择订阅方案后即可解锁结算。",
        noPlanSelectedTitle: "未选择套餐",
    },
    stageShell: {
        actionLabel: "操作类型",
        availablePlansLabel: "可选套餐",
        checkoutAmountLabel: "结算金额",
        checkoutDescription: "当前套餐已经锁定进入支付阶段，优惠券、应付金额和支付方式都会与该套餐保持同步，直到结算完成。",
        checkoutStatusDescription: "如需切换套餐，请先返回套餐阶段。",
        checkoutTitle: "锁定结算",
        couponsReadyLabel: "可用优惠",
        currentLevelLabel: "当前等级",
        descriptionLockedPackage: "返回上一阶段后可重新选择套餐，再继续结算。",
        descriptionNoPlanSelected: "请先选择一个订阅套餐后再进入结算。",
        durationLabel: "时长",
        includedPointsLabel: "赠送算力积分",
        lockedBadge: "已锁定套餐",
        lockedPackageLabel: "锁定套餐",
        planStageDescription: "先完成套餐比较与选择，再在真正准备支付时进入结算阶段，保持与 Sdkwork Studio 一致的高级购买节奏。",
        planStageTitle: "选择高级会员套餐",
        plannedActionLabel: "计划操作",
        priceLabel: "价格",
        purchaseStagesEyebrow: "购买阶段",
        readyDescription: "进入结算后套餐详情会被锁定，但在支付前你仍可以返回此阶段重新切换套餐。",
        readyTitle: "准备继续",
        selectedPackageLabel: "已选套餐",
        signInRequiredDescription: "登录前也可以先浏览和比较套餐，登录后即可继续结算。",
        signInRequiredTitle: "需要登录",
        stepCheckoutDescription: "锁定套餐、应用优惠并完成支付确认。",
        stepCheckoutTitle: "2. 结算支付",
        stepPlanDescription: "先比较免费版与高级版，再决定进入支付。",
        stepPlanTitle: "1. 选择套餐",
        twoStepFlow: "两步购买流",
    },
    service: {
        checkoutFailed: "订阅结算失败。",
        loadDashboardFailed: "加载订阅中心失败。",
        purchaseFailed: "购买订阅失败。",
        renewFailed: "续费订阅失败。",
        requestFailed: "请求失败。",
        selectPlanBeforeContinue: "请先选择订阅方案。",
        signInRequired: "请先登录后再管理订阅。",
        upgradeFailed: "升级订阅失败。",
    },
    status: {
        available: "可用",
        expired: "已过期",
        inactive: "未激活",
        used: "已使用",
    },
};
const SDKWORK_SUBSCRIPTION_MESSAGES = {
    "en-US": EN_US_MESSAGES,
    "zh-CN": ZH_CN_MESSAGES,
};
export function normalizeSdkworkSubscriptionLocale(locale) {
    const normalized = String(locale || "").trim().toLowerCase();
    if (normalized.startsWith("zh")) {
        return "zh-CN";
    }
    return "en-US";
}
export function createSdkworkSubscriptionMessages(locale, overrides) {
    return mergeDeep(SDKWORK_SUBSCRIPTION_MESSAGES[normalizeSdkworkSubscriptionLocale(locale)], overrides);
}
//# sourceMappingURL=subscription-copy.js.map